version: "3.4"

services:
  eventstore.db.monitor:
    image: eventstore/eventstore:release-5.0.8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_DB=/var/lib/eventstore-data
      - EVENTSTORE_INDEX=/var/lib/eventstore-index
      - EVENTSTORE_LOG=/var/log/eventstore
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore-data
      - type: volume
        source: eventstore-volume-index
        target: /var/lib/eventstore-index
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  prometheus:
    image: prom/prometheus:v2.19.0
    command:
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --config.file=/etc/prometheus/promo/prometheus.yml
      - --web.enable-lifecycle
      - --web.enable-admin-api
    volumes:
      - ./common:/etc/prometheus/
    ports:
      - 9090:9090

    networks:
      - default

  event_monitor:
    image: event-monitor
    environment:
      - EVENTSTORE_URL=http://eventstore.db.monitor:2113
      - CLUSTER_MODE=single
      - EVENTSTORE_USER=admin
      - EVENTSTORE_PASSWORD=changeit
    ports:
      - 9448:9448

    networks:
      - default

  grafana:
    image: grafana/grafana:7.0.3
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000

networks:
  default:
    external:
      name: scraper

volumes:
  grafana-volume:
  eventstore-volume-data:
  eventstore-volume-index:
  eventstore-volume-logs:
